version: '3'
services:
  backupmongo:
#    image: backupmongo:1.0
    build: .
    command: python app.py
    ports:
      - 3064:8000
    volumes:
      - /usr/local/volumes/backupmongo/tmp:/tmp
      - /usr/local/volumes/backupmongo/dbs:/dbs


