version: '3'
services:
  app:
#    image: backupmongo:1.0
    build: .
    command: python app.py
    ports:
      - 3064:8000
    volumes:
      - backupmongo_dbs:/app/dbs
      - backupmongo_tmp:/app/tmp

volumes:
  backupmongo_dbs:
  backupmongo_tmp:
