version: '3'
services:
  app:
    #    image: backupmongo:1.0
    build: .
    command: python app.py
    ports:
      - 3064:8000
    volumes:
      - backupmongo_dbs:/app/dbs
      - backupmongo_tmp:/app/tmp
#    logging:
#      driver: "json-file"
#      options:
#        max-file: 5
#        max-size: 10m
#        labels: backupmongo

    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://207.244.232.99:4040"


volumes:
  backupmongo_dbs:
  backupmongo_tmp:
