version: '3'
services:
  app:
    build: .
    command: uvicorn main:app --host "0.0.0.0" --port 8000 --log-level "info" --reload
    ports:
      - 3064:8000
    volumes:
      - backupmongo_dbs:/app/dbs
      - backupmongo_tmp:/app/tmp
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
        labels: backupmongo

volumes:
  backupmongo_dbs:
  backupmongo_tmp:
