version: '3'
services:
  backupmongo:
#    image: backupmongo:1.0
    build: .
    command: python app.py
    ports:
      - 3064:8000
    volumes:
      - backupmongo_dbs:/dbs
      - backupmongo_tmp:/tmp

volumes:
  backupmongo_dbs:
  backupmongo_tmp:
